### ISSUE TITLE
Question - Copy of EccoExt

### ISSUE THREAD

**Issue by JavaScriptDude** [gltarsa/dotfiles#1]
Is there any chance you have a copy of the working Ecco Ext in its zip file as it was originally supplied on the yahoo forums? I only have the executable but want to re-publish the original zip for historical purposes and to assist others in getting EccoPro working on Linux.

I've tried contacting the original author but no response.

Thanks!

**Comment by gltarsa** [comment]
All I can find are two RAR files, which I  believe are original for versions 4.3.0.6 (2/18/2011) and 4.5.7.0 (9/8/2011).

Will either of them be helpful?

# ls -l eccoext
total 1132
512 -rw-rw-r-- 1 tarsa family 522859 Feb 18  2010 eccoext4.3.0.6.rar
  0 drwxrwxr-x 1 tarsa family    108 Sep  8  2011 eccoext4.5.7.0/
620 -rw-rw-r-- 1 tarsa family 630972 Sep  8  2011 eccoext4.5.7.0.rar

**Comment by JavaScriptDude** [comment]
What timing, I was just able to get a copy of the latest version of 4.6.7.7 from https://groups.io/g/EccoPro/files just 10 minutes ago (requires registration).

I checked the sha256 hash of the exe and it matches the one I have on my computers so looks like I'm good.

Thanks for checking!

FYI:
eccoext.exe (v4.6.7.7):
- md5: c5b5a0a3a603a0c620cc10b21000ac3f
- sha1: b2e5b0d6f35a200c1287c19066faf5c81b1a61cf
- sha256: b91b12b6dd54551cc405ae2f3a3d026e9a7f6545d3ac030eb651f36524db6ec1
- VT Permalink: https://www.virustotal.com/gui/file/b91b12b6dd54551cc405ae2f3a3d026e9a7f6545d3ac030eb651f36524db6ec1/detection/f-b91b12b6dd54551cc405ae2f3a3d026e9a7f6545d3ac030eb651f36524db6ec1-1600801115

eccoext.zip from groups.io:
- md5: b2a61a082d59f335d068c75e009be8eb
- sha1: 39af1cc4e9e24a589707ffa0960ed0bdb9460c86
- sha256: d545c9813627200a2965ae1ee3f431ad7bb35eb1a3c6d6b999efb568b53534bc
- VT Permalink: https://www.virustotal.com/gui/file/d545c9813627200a2965ae1ee3f431ad7bb35eb1a3c6d6b999efb568b53534bc/detection/f-d545c9813627200a2965ae1ee3f431ad7bb35eb1a3c6d6b999efb568b53534bc-1610988122

**Comment by JavaScriptDude** [comment]
For people who land here, this is a comment I added to VirusTotal:

> The Virus detection's of this may be false positives. This program does highly dynamic work to patch issues with an ancient executable Eccopro.exe that was last compiled back in 1997 but is still used to this day by many. This dynamic work would likely raise all kinds of flags with basic virus scanners. See https://en.wikipedia.org/wiki/Ecco_Pro and notes regarding Ecco Extension and Scott Rosenberg (slangmgh).

**Comment by gltarsa** [comment]
My pleasure.  How did you manage to get connected to me?  Just curious.

-G

**Comment by JavaScriptDude** [comment]
I scraped github for references to eccoext =)
